

#ifndef IMAGE_ENHANCEMENT_IMPLEMENTATION_IMAGEENHANCER_H
#define IMAGE_ENHANCEMENT_IMPLEMENTATION_IMAGEENHANCER_H

#include <map>
class ImageEnhancer {
public:
    int run();
private:
};


#endif //IMAGE_ENHANCEMENT_IMPLEMENTATION_IMAGEENHANCER_H
